server:
  port: 8081

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8080/eureka/

spring:
  application:
    name: integral_rule
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

rule:
  id: 0
